### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by mmalisz** [Amelandbor/service.subtitles.addic7ed#12]
I am getting this error while trying to search anything:
http://pastebin.com/raw/980tCPWu
I am running LibreELEC 7.0.2 on RaspberryPi 2.
Afaik LE7 uses Kodi 16 (Jarvis).

**Comment by Amelandbor** [comment]
Can you try setting your preferred language to a language in the subtitle settings?

Also are you using the latest version?

**Comment by mmalisz** [comment]
Latest version of the LE, or the service? If LE, I think 7.0.3 is available, while I am running 7.0.2.
If the service, I've added it on 16.01.2017 (at least the LE filesystem states that date).

About preferred language, will give you feedback when I am back from work.

**Comment by mmalisz** [comment]
Well, I set the preferred language and I've successfully found subtitles for The Big Bang Theory, but tried with Elementary and had an error. Then I had removed the plugin via system and reinstalled using the current zip. Now it worked for 3 / 3 trials.
Well, I guess I can close it for now. Will reopen if the issue comes back.
