### ISSUE TITLE
Can't find subtitles on kodi 16.1

### ISSUE THREAD

**Issue by MaikoHermans** [Amelandbor/service.subtitles.addic7ed#6]
I'm trying to run the addon on kodi 16.1, however I get an error message saying "manual search is not enabled currently". BeautifulSoup is enabled. Is this not supported yet with 16.1?

**Comment by Amelandbor** [comment]
Like it says manual search isn't coded. But it should work fine if your files are scanned into the library.

**Comment by MaikoHermans** [comment]
No it will just say that it can't find any subtitles. By scanned into the library you mean that you added the folder to it and selected the video from there on? I've tried multiple episodes from different shows where I'm sure addic7ed has the subtitles for. Last weeks big bang theory for example

**Comment by Amelandbor** [comment]
It sounds like they aren't scanned into the video library and you just play them from the folder. That way there is no information available to kodi about the tv show name, season and episode number. 

Filename search is available but it isn't that good tbh.

You can always post a debug log so I can see what's going wrong.

**Comment by MaikoHermans** [comment]
I've just tried the opensubtitles addon and that is able to find the subtitles. I just added a source path for the video's I'm not sure if I'm supposed to go at it a different way. I'm new to kodi.

I think this is what you are looking for:

`12:38:12 T:14316   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Addic7ed.com('plugin://service.subtitles.addic7ed/','25','?action=search&languages=English&preferredlanguage=Unknown')
12:38:12 T:14316   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the Addic7ed.com (id=27) plugin...
12:38:12 T:12644   DEBUG: Thread LanguageInvoker start, auto delete: false
12:38:12 T:12644    INFO: initializing python engine.
12:38:12 T:12644   DEBUG: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): start processing
12:38:12 T:12644   DEBUG: -->Python Interpreter Initialized<--
12:38:12 T:12644   DEBUG: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): the source file to load is "C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py"
12:38:12 T:12644   DEBUG: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): setting the Python path to C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed;C:\Users\mwmhe\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
12:38:12 T:12644   DEBUG: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): entering source directory C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed
12:38:12 T:12644   DEBUG: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): instantiating addon using automatically obtained id of "service.subtitles.addic7ed" dependent on version 2.14.0 of the xbmc.python api
12:38:12 T:12644   DEBUG: ### [__main__] - Search_addic7ed='{'mansearch': False, 'episode': '', 'temp': False, 'title': 'elementary.422.hdtv-lol[ettv].mkv', 'season': '', 'tvshow': '', 'rar': False, 'year': '', 'file_original_path': u'C:\\Users\\mwmhe\\Downloads\\Elementary.S04E22.HDTV.x264-LOL[ettv]\\elementary.422.hdtv-lol[ettv].mkv', '3let_language': ['eng']}', filename='elementary.422.hdtv-lol[ettv]', addon_version=1.0.0
12:38:12 T:12644   DEBUG: ### [__main__] - clean title: "elementary 422" ()
12:38:12 T:12644   DEBUG: POParser: PO file has Win Style Line Endings. Converted in memory to Linux LF for file: C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\resources\language\English\strings.po
12:38:12 T:12644   DEBUG: POParser: loaded 4 strings from file C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\resources\language\English\strings.po
12:38:12 T:12644    INFO: CPythonInvoker(27, C:\Users\mwmhe\AppData\Roaming\Kodi\addons\service.subtitles.addic7ed\service.py): script successfully run
12:38:12 T:14316   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult- plugin returned successfully
12:38:12 T:12644    INFO: Python script stoppe`

**Comment by Amelandbor** [comment]
Yeah, the video isn't scanned into the library.
I recommend setting up a video library with your TV shows. 

http://kodi.wiki/view/Adding_video_sources

**Comment by MaikoHermans** [comment]
alright my bad I did just do that before you mentioned it but it's only able to recognize like 10% off all the tv shows I have

**Comment by Amelandbor** [comment]
Take a look at naming conventions 

http://kodi.wiki/view/Naming_video_files/TV_shows

You can take a look at some tools to get it all organized. For example: [sickbeard](http://www.sickbeard.com), [therenamer](http://www.therenamer.com/) or [tvrename](http://tvrename.com/)

**Comment by cudencuden** [comment]
so no plan to support searching for subs if you are just streaming from web sources?
