### ISSUE TITLE
Some downloads work, others don't

### ISSUE THREAD

**Issue by zewindsor** [Amelandbor/service.subtitles.addic7ed#7]
Hi everybody,

I have some problems with addic7ed addon. I use it on the last version of Kodi (16.1), to download subtitles from tv shows.
All my tv shows are downloaded with Sickbeard and Sabnzbd, categorized as TV Shows in Kodi. So each file has a correct format name, with its .nfo.

The addon gives errors for some shows, and works for others. I attached an example of log file :
[kodi.log.txt](https://github.com/Amelandbor/service.subtitles.addic7ed/files/568487/kodi.log.txt)
It seems to have a timeout error but the computer can reach Addic7ed without troubles. Moreover, when I search the subtitle directly on Addic7ed website, I find it.

I first thought to a limitation from Addic7ed (even if I must download 2 or 3 subtitles max per day), but the bug always occurs on the same files and the addon always works on the same files.
I tried to change languages in Kodi settings, adding english, but it doesn't work better.

If someone has an idea to help me, I take it :)

Thanks.

**Comment by Amelandbor** [comment]
@zewindsor I've quickly updated the timeout settings to 20 seconds, can you try if that works for you?

**Comment by zewindsor** [comment]
@Amelandbor gg :+1: Indeed it works now :) Big thanks !

Nevertheless, I wonder if there is a problem with Kodi. Since Addic7ed wasn't working, I tried with Opensubtitles and Podnapisi. The two return no results for the same files which make Addic7ed crashes, and the two return good results for the same files with which Addic7ed is ok...

**Comment by Amelandbor** [comment]
Did you check if those existed on their sites?

Glad it works now :)

**Comment by zewindsor** [comment]
At least on Podnapisi yes. It's the season of a tv show currently aired.

**Comment by Amelandbor** [comment]
Weird, but I don't think it has anything to do with Kodi itself, maybe something to do with the title of those episodes.
